[workspace]

members = [
    "utils",
    "schnorr_pok",
    "bbs_plus",
    "vb_accumulator",
    "proof_system",
    "saver",
    "compressed_sigma",
    "benches",
    "test_utils"
]

[profile.release]
lto = true

[profile.bench]
lto = true
