[package]
name = "bbs_plus"
version = "0.3.0"
edition = "2018"
authors = ["Dock.io"]
license = "Apache-2.0"
description = "BBS+ signature and protocol for proof of knowledge of signature"
repository = "https://github.com/docknetwork/crypto"

[lib]
doctest = false
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
ark-serialize = { version = "^0.3.0", default-features = false, features = [ "derive" ] }
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
digest = "0.9"
rayon = { version = "1", optional = true }
schnorr_pok = { version = "0.3.0", default-features = false, path = "../schnorr_pok" }
dock-crypto-utils = { version = "0.1.0", default-features = false, path = "../dock-crypto-utils" }

[dev-dependencies]
blake2 = { version = "0.9", default-features = false }
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }

[features]
default = [ "std", "parallel" ]
std = [ "ark-ff/std", "ark-ec/std", "ark-std/std", "ark-serialize/std", "schnorr_pok/std", "dock-crypto-utils/std"]
print-trace = [ "ark-std/print-trace", "schnorr_pok/print-trace", "dock-crypto-utils/print-trace" ]
parallel = [ "std", "ark-ff/parallel", "ark-ec/parallel", "ark-std/parallel", "rayon", "schnorr_pok/parallel"]