[package]
name = "proof_system"
version = "0.10.0"
edition = "2021"
authors = ["Dock.io"]
license = "Apache-2.0"
description = "Proof system to comprise various cryptographic primitives"
repository = "https://github.com/docknetwork/crypto"

[lib]
doctest = false
path = "src/lib.rs"

[dependencies]
ark-serialize = { version = "^0.3.0", default-features = false, features = [ "derive" ] }
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
digest = "0.9"
rayon = { version = "1", optional = true }
bbs_plus = { version = "0.6.0", default-features = false, path = "../bbs_plus" }
schnorr_pok = { version = "0.5.0", default-features = false, path = "../schnorr_pok" }
vb_accumulator = { version = "0.7.0", default-features = false, path = "../vb_accumulator" }
dock_crypto_utils = { version = "0.4.0", default-features = false, path = "../utils" }
saver = { version = "0.2.0", default-features = false, path = "../saver" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_with = { version = "1.10.0", default-features = false, features = ["macros"] }
ark-groth16 = { version = "^0.3.0", default-features = false }
ark-r1cs-std = { version = "^0.3.0", default-features = false }
ark-relations = { version = "^0.3.0", default-features = false }

[dependencies.legogroth16]
git = "https://github.com/lovesh/legogro16"
#branch = "comm-wit"
rev = '00dfaf6e75464b8a246db7912eeb48070d10e067'
default-features = false

[dev-dependencies]
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
blake2 = { version = "0.9", default-features = false }
serde_json = "1.0"
test_utils = { version = "0.1.0", default-features = false, path = "../test_utils" }

[features]
default = [ "parallel" ]
std = [ "ark-ff/std", "ark-ec/std", "ark-std/std", "ark-serialize/std", "schnorr_pok/std", "dock_crypto_utils/std", "serde/std", "saver/std", "ark-groth16/std", "legogroth16/std", "ark-r1cs-std/std", "ark-relations/std" ]
print-trace = [ "ark-std/print-trace", "schnorr_pok/print-trace", "bbs_plus/print-trace", "vb_accumulator/print-trace", "dock_crypto_utils/print-trace" ]
parallel = [ "std", "ark-ff/parallel", "ark-ec/parallel", "ark-std/parallel", "rayon", "schnorr_pok/parallel", "bbs_plus/parallel", "vb_accumulator/parallel", "saver/parallel", "ark-groth16/parallel", "legogroth16/parallel", "ark-r1cs-std/parallel", "dock_crypto_utils/parallel" ]